Repository graphql-python/gql, pull requests merged in 2020-07, with the labels that each got.

#109 Improve messages for `NotImplementedError`s in AsyncTransport abstract class.
  gql/transport/async_transport.py
Labels: type: documentation

#110 Ignore keepalives before connection_ack in websockets transport
  gql/transport/websockets.py
  tests/test_websocket_exceptions.py
  tests/test_websocket_query.py
Labels: type: bug

#99 Graceful shutdown for synchronous subscriptions
  gql/client.py
  tests/test_websocket_subscription.py
Labels: type: maintenance, type: tests

#113 type_def argument of Client is now deprecated.
  gql/client.py
  tests/starwars/test_validation.py
  tests/test_async_client_validation.py
Labels: type: feature

#114 Doc update readme
  README.md
Labels: type: documentation

#124 chore: add GitHub Actions
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .travis.yml
  tox.ini
Labels: type: chore

#121 Raises `KeyError` when argument is invalid.
  gql/dsl.py
  tests/starwars/test_dsl.py
Labels: type: bug
