Repository graphql-python/gql, pull requests merged in 2020-09, with the labels that each got.

#135 Fix running execute and subscribe of client in a new Thread
  gql/client.py
  gql/transport/websockets.py
  tests/conftest.py
  tests/test_aiohttp.py
  tests/test_requests.py
  tests/test_websocket_subscription.py
Labels: type: bug

#100 Adding a new transport class to handle Phoenix channels
  gql/__init__.py
  gql/transport/phoenix_channel_websockets.py
  gql/transport/websockets.py
  tests/conftest.py
  tests/test_async_client_validation.py
  tests/test_phoenix_channel_exceptions.py
  tests/test_phoenix_channel_query.py
  tests/test_phoenix_channel_subscription.py
  tests/test_websocket_exceptions.py
  tests/test_websocket_query.py
  tests/test_websocket_subscription.py
Labels: lib: phoenix, status: waiting for author, type: feature, type: tests

#117 chore: generate docs with sphinx
  MANIFEST.in
  Makefile
  docs/Makefile
  docs/advanced/async_advanced_usage.rst
  docs/advanced/dsl_module.rst
  docs/advanced/index.rst
  docs/advanced/local_schema.rst
  docs/async/async_intro.rst
  docs/async/async_usage.rst
  docs/async/index.rst
  docs/code_examples/aiohttp_async.py
  docs/code_examples/aiohttp_sync.py
  docs/code_examples/requests_sync.py
  docs/code_examples/websockets_async.py
  docs/conf.py
  docs/index.rst
  docs/intro.rst
  docs/make.bat
  docs/modules/client.rst
  docs/modules/gql.rst
  docs/modules/transport.rst
  docs/requirements.txt
  docs/transports/aiohttp.rst
  docs/transports/async_transports.rst
  docs/transports/index.rst
  docs/transports/phoenix.rst
  docs/transports/requests.rst
  docs/transports/sync_transports.rst
  docs/transports/websockets.rst
  docs/usage/basic_usage.rst
  docs/usage/headers.rst
  docs/usage/index.rst
  docs/usage/subscriptions.rst
  docs/usage/validation.rst
  docs/usage/variables.rst
  gql/__init__.py
  gql/client.py
  gql/gql.py
  gql/transport/aiohttp.py
  gql/transport/phoenix_channel_websockets.py
  gql/transport/requests.py
  gql/transport/websockets.py
  setup.py
  tox.ini
Labels: type: chore, type: documentation
