Repository graphql-python/gql, pull requests merged in 2020-11, with the labels that each got.

#158 Optional dependencies for transports
  .github/workflows/tests.yml
  Makefile
  README.md
  docs/async/async_usage.rst
  docs/code_examples/aiohttp_async.py
  docs/code_examples/aiohttp_sync.py
  docs/code_examples/requests_sync.py
  docs/code_examples/websockets_async.py
  docs/intro.rst
  docs/transports/phoenix.rst
  docs/transports/requests.rst
  docs/usage/subscriptions.rst
  gql/__init__.py
  gql/cli.py
  setup.py
  tests/conftest.py
  tests/test_aiohttp.py
  tests/test_aiohttp_online.py
  tests/test_async_client_validation.py
  tests/test_cli.py
  tests/test_client.py
  tests/test_http_async_sync.py
  tests/test_phoenix_channel_exceptions.py
  tests/test_phoenix_channel_query.py
  tests/test_phoenix_channel_subscription.py
  tests/test_requests.py
  tests/test_transport.py
  tests/test_websocket_exceptions.py
  tests/test_websocket_online.py
  tests/test_websocket_query.py
  tests/test_websocket_subscription.py
Labels: type: feature

#167 REFACTOR fetch schema at start of session
  docs/usage/validation.rst
  gql/client.py
  tests/fixtures/vcr_cassettes/client.yaml
  tests/fixtures/vcr_cassettes/queries.yaml
Labels: type: optimization

#166 Update aiohttp from ==3.7.1 to >=3.7.1
  setup.py
Labels: type: maintenance

#169 Refactor DSL code
  README.md
  docs/advanced/dsl_module.rst
  docs/code_examples/aiohttp_async_dsl.py
  docs/code_examples/requests_sync.py
  docs/code_examples/requests_sync_dsl.py
  docs/modules/client.rst
  docs/modules/dsl.rst
  docs/modules/gql.rst
  docs/modules/transport.rst
  gql/dsl.py
  tests/conftest.py
  tests/nested_input/schema.py
  tests/nested_input/test_nested_input.py
  tests/starwars/test_dsl.py
Labels: type: feature
