Repository graphql-python/gql, pull requests merged in 2020-10, with the labels that each got.

#139 Add option to send parameters in gql-cli
  scripts/gql-cli
Labels: type: feature

#151 DSL: Allow to use GraphQL keys named type
  gql/dsl.py
Labels: type: bug

#152 chore: add os matrix to tests action workflow
  .github/workflows/tests.yml
Labels: type: chore

#145 File support
  README.md
  docs/transports/aiohttp.rst
  docs/usage/file_upload.rst
  docs/usage/index.rst
  gql/transport/aiohttp.py
  gql/utils.py
  tests/conftest.py
  tests/test_aiohttp.py
Labels: type: documentation, type: feature

#148 improved gql-cli script
  Makefile
  docs/conf.py
  docs/gql-cli/intro.rst
  docs/index.rst
  gql/cli.py
  scripts/gql-cli
  setup.py
  tests/conftest.py
  tests/test_aiohttp.py
  tests/test_cli.py
  tests/test_websocket_exceptions.py
  tests/test_websocket_query.py
Labels: type: feature

#159 Update aiohttp from 3.6.2 to 3.7.1
  setup.py
Labels: type: maintenance

#160 chore: stable Python 3.9 support
  .github/workflows/tests.yml
  setup.py
  tox.ini
Labels: type: chore

#157 Feature aiohttp and requests transports logging
  docs/advanced/index.rst
  docs/advanced/logging.rst
  gql/transport/aiohttp.py
  gql/transport/requests.py
Labels: type: documentation, type: feature

#165 DOC Adding IPython section
  docs/async/async_usage.rst
Labels: type: documentation
